#!/usr/bin/env python2

import argparse
import logging
import sys

import gtk
import dbus
import dbus.service

from dbus.mainloop.glib import DBusGMainLoop

from notificationd.api import *

__description__ = 'Trigger desktop notifications through the system dbus'

_d_debug = False

ll2str = {
    10: 'DEBUG',
    20: 'INFO',
    30: 'WARNING',
    40: 'ERROR',
    50: 'CRITICAL'
}

def main():
    parser = argparse.ArgumentParser(description=__description__)
    parser.add_argument('-D', dest='debug', action='store_true',
        default=_d_debug, help='Enable debugging')

    args = parser.parse_args()

    logger = logging.getLogger('main')
    if args.debug:
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO
    logger.setLevel(log_level)

    console_logger = logging.StreamHandler()
    console_logger.setLevel(log_level)
    formatter = logging.Formatter('%(asctime)s [%(levelname)s]: %(message)s')
    console_logger.setFormatter(formatter)
    logger.addHandler(console_logger)

    logger.debug('logging at %s' % ll2str[log_level])

    DBusGMainLoop(set_as_default=True)
    dbus_server = NotificationDBusServer(logger)
    gtk.main()

    return

if __name__ == '__main__':
    sys.exit(main())
